apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: machineclass
  namespace: migration
providerSpec:       # Learn about this field in release notes. This is basically a blob for provider-specific spec.
  ami: ami-01234567
  blockDevices:
  - ebs:
      volumeSize: 50
      volumeType: gp2
  iam:
    name: shoot--demo-proj--grpc-test-nodes
  keyName: shoot--demo-proj--grpc-test-ssh-publickey
  machineType: m4.large
  networkInterfaces:
  - securityGroupIDs:
    - sg-12345612345567
    subnetID: subnet-123456123456
  region: eu-west-1
  secretRef:
    name: grpc-secret
    namespace: migration
  tags:
    kubernetes.io/cluster/shoot--demo-proj--grpc-test: "1"
    kubernetes.io/role/mcmtest: "1"
secretRef:
  name: grpc-secret
  namespace: migration