apiVersion: v1
items:
- apiVersion: machine.sapcloud.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      name: machine-deployment-old
    name: machine-deployment-old-86df5ddd9c-2j869
    namespace: migration
  spec:
    class:
      kind: MachineClass    # Updated from AWSMachineClass
      name: machineclass
    providerID: aws:///eu-west-1/i-1234  # To relate this Machineobject with actual VM
  status:
    node: ip-10-ABC-13-XYZ.eu-west-1.compute.internal   # To relate this Machineobject with node-object in kubernetes.
- apiVersion: machine.sapcloud.io/v1alpha1
  kind: Machine
  metadata:
    labels:
      name: machine-deployment-old
    name: machine-deployment-old-86df5ddd9c-9p72f
    namespace: migration
  spec:
    class:
      kind: MachineClass    #Updated from AWSMachineClass
      name: machineclass
    providerID: aws:///eu-west-1/i-12345  # To relate this Machineobject with actual VM
  status:
    node: ip-10-ABC-0-XYZ.eu-west-1.compute.internal  # To relate this Machineobject with node-object in kubernetes.
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
