apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineDeployment
metadata:
  name: machine-deployment-old
  namespace: migration
spec:
  minReadySeconds: 500
  replicas: 2
  selector:
    matchLabels:
      name: machine-deployment-old
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: machine-deployment-old
    spec:
      class:
        kind: MachineClass  #Updated from AWSMachineClass
        name: machineclass